name: 'GitHub Actions BingPicApi'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 16 * * *'
jobs:
  Bing-spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        timeout-minutes: 350
        run: bash ./main.sh
      - name: Commit files
        run: |
          git config --local user.email "1302070253@qq.com"
          git config --local user.name "mylong123"
          git add -A
          git commit -m "?? add a BingPic" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: 'Create a Release'
        uses: elgohr/Github-Release-Action@master
        env:
          REPO: https://github.com/mylong123/bingpic.git
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          # BRANCH: gh-pages
        with:
          args: BingImage