name: 'GitHub Actions BingPicApi'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 16 * * *'
jobs:
  Bing-spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # 否则,是GITHUB_TOKEN使用的令牌,而不是你个人的令牌
          fetch-depth: 0 # 否则,你将参未能推动回购不在座位上
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        timeout-minutes: 350
        run: bash ./main.sh
      - name: Commit files
        run: |
          git config --local user.email "1302070253@qq.com"
          git config --local user.name "mylong123"
          git rm -r --cached
          # git add -A
          git add .
          git commit -m "?? add a BingPic" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          repository: mylong123/bing-pic
          branch: master
          force: true
          directory: .
      - name: 'Create a Release'
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          # BRANCH: gh-pages
        with:
          args: BingImage
      #提交到page
      # - name: Push page
      #   uses: s0/git-publish-subdir-action@master
      #   env:
      #     REPO: git@github.com:mylong123/bing-pic.git
      #     BRANCH: master
      #     FOLDER: tmp
      #     SSH_PRIVATE_KEY: ${{ secrets.SSHTOKEN }}